name: Update CVEs (full)

on:
  workflow_dispatch:
  schedule:
  - cron: "34 4 * * *"
permissions: {}

jobs:
  update-cves:
    name: Update CVEs (full)
    uses: ./.github/workflows/cve-import.yaml
    permissions:
      contents: write
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    with:
      full_import: true
