name: Update CVEs

on:
  workflow_dispatch:
  schedule:
  - cron: "13 */2 * * *"
permissions: {}
concurrency: update-cves

jobs:
  update-cves:
    name: Update CVEs
    permissions:
      contents: write
    uses: ./.github/workflows/cve-import.yaml
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    with:
      full_import: false
