name: Update CVEs (full)

on:
  workflow_dispatch:
  schedule:
  - cron: "34 4 * * *"
permissions: {}

jobs:
  update-cves:
    name: Update CVEs (full)
    uses: ./.github/workflows/cve-import.yaml
    permissions:
      contents: write
    secrets: inherit
    with:
      full_import: true
